"""Model transfer and offline benchmark provisioning tool.

Used to export discovered models and benchmark scores from an internet-connected
machine into an Alembic migration script, which can then be applied on an
air-gapped environment (e.g. UAT).

Usage:
  1. On the internet-connected machine with populated benchmarks, run:
     python -m ai_qa.admin.model_transfer make-migration --out-dir alembic/versions
  2. Commit the generated migration and deploy to UAT.
  3. On the air-gapped host (UAT), run migrations to apply:
     alembic upgrade head
"""

import argparse
import datetime
import sys
import uuid
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import Session

from ai_qa.db.models import DiscoveredModelSnapshot, ModelBenchmarkScore
from ai_qa.db.session import create_session_factory


def get_current_alembic_head() -> str:
    """Read the alembic head from alembic/versions."""
    # This is a bit of a hack, but we'll try to use alembic if available
    try:
        from alembic.config import Config
        from alembic.script import ScriptDirectory

        alembic_cfg = Config("alembic.ini")
        script = ScriptDirectory.from_config(alembic_cfg)
        head = script.get_current_head()
        return head or ""
    except Exception:
        return ""


def generate_migration_content(db: Session, down_revision: str) -> str:
    discovered_models = (
        db.execute(select(DiscoveredModelSnapshot).order_by(DiscoveredModelSnapshot.model_id))
        .scalars()
        .all()
    )

    scores = (
        db.execute(
            select(ModelBenchmarkScore).order_by(
                ModelBenchmarkScore.model_id, ModelBenchmarkScore.capability
            )
        )
        .scalars()
        .all()
    )

    discovered_list_str = ",\n".join(
        f"    ({repr(dm.model_id)}, {repr(dm.display_name)}, {repr(dm.supports_vision)})"
        for dm in discovered_models
    )

    scores_list_str = ",\n".join(
        f"    ({repr(s.model_id)}, {repr(s.capability)}, {repr(s.score)})" for s in scores
    )

    rev_id = uuid.uuid4().hex[:12]
    create_date = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M:%S")

    return f'''"""seed discovered models and benchmark scores (refresh)

Regenerated snapshot of the admin model-benchmark dashboard data (discovered-model
snapshot + per-capability scores), captured from a machine WITH internet access, for
deployments (e.g. UAT) that cannot run the live "Sync models and benchmarks". Unlike the
initial seed, this REFRESHES: discovered rows are upserted and ALL prior benchmark
scores are deleted and replaced, mirroring the live sync's overwrite policy.

Auto-generated by ``python -m ai_qa.admin.model_transfer make-migration``.

Revision ID: {rev_id}
Revises: {down_revision}
Create Date: {create_date}
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "{rev_id}"
down_revision: str | Sequence[str] | None = "{down_revision}"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# (model_id, display_name, supports_vision)
_DISCOVERED: list[tuple[str, str | None, bool | None]] = [
{discovered_list_str}
]

# (model_id, capability, score)
_SCORES: list[tuple[str, str, float]] = [
{scores_list_str}
]


def _discovered_table() -> sa.TableClause:
    return sa.table(
        "discovered_models",
        sa.column("id", sa.Uuid),
        sa.column("model_id", sa.String),
        sa.column("display_name", sa.String),
        sa.column("supports_vision", sa.Boolean),
        sa.column("last_seen_at", sa.DateTime(timezone=True)),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )


def _scores_table() -> sa.TableClause:
    return sa.table(
        "model_benchmark_scores",
        sa.column("id", sa.Uuid),
        sa.column("model_id", sa.String),
        sa.column("capability", sa.String),
        sa.column("score", sa.Float),
        sa.column("note", sa.Text),
        sa.column("updated_by_user_id", sa.Uuid),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    from sqlalchemy.dialects.postgresql import insert as pg_insert

    now = sa.func.now()
    new_uuid = sa.func.gen_random_uuid()
    discovered = _discovered_table()
    for model_id, display_name, supports_vision in _DISCOVERED:
        op.execute(
            pg_insert(discovered)
            .values(
                id=new_uuid,
                model_id=model_id,
                display_name=display_name,
                supports_vision=supports_vision,
                last_seen_at=now,
                created_at=now,
                updated_at=now,
            )
            .on_conflict_do_update(
                index_elements=["model_id"],
                set_={{
                    "display_name": display_name,
                    "supports_vision": supports_vision,
                    "last_seen_at": now,
                    "updated_at": now,
                }},
            )
        )

    # TRUE replace-snapshot: Delete ALL prior on-prem scores before inserting new ones.
    # This prevents orphaned rows if a model was removed from the snapshot.
    op.execute(sa.text("DELETE FROM model_benchmark_scores"))

    scores = _scores_table()
    for model_id, capability, score in _SCORES:
        op.execute(
            pg_insert(scores).values(
                id=new_uuid,
                model_id=model_id,
                capability=capability,
                score=score,
                note=None,
                updated_by_user_id=None,
                created_at=now,
                updated_at=now,
            )
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    op.execute(sa.text("DELETE FROM model_benchmark_scores"))
'''


def make_migration(out_dir: str | None = None) -> None:
    """Generate the migration script."""
    head = get_current_alembic_head()
    if not head:
        print("Warning: Could not determine current Alembic head.", file=sys.stderr)

    session_factory = create_session_factory()
    db = session_factory()
    try:
        content = generate_migration_content(db, head)
    finally:
        db.close()

    if out_dir:
        rev_id = [line for line in content.splitlines() if line.startswith("revision: ")][0].split(
            '"'
        )[1]
        out_path = Path(out_dir) / f"{rev_id}_seed_model_benchmarks_refresh.py"
        out_path.write_text(content, encoding="utf-8")
        print(f"Migration saved to {out_path}")
    else:
        print(content)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Model transfer and offline benchmark provisioning."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    make_mig_parser = subparsers.add_parser(
        "make-migration", help="Export models and scores to an Alembic migration"
    )
    make_mig_parser.add_argument(
        "--out-dir",
        "-o",
        type=str,
        help="Output directory for the migration script (e.g. alembic/versions)",
    )

    args = parser.parse_args()
    if args.command == "make-migration":
        make_migration(getattr(args, "out_dir", None))


if __name__ == "__main__":
    main()
