"""add confluence_base_url to project

Revision ID: 02eee99fe6ae
Revises: 80b390245151
Create Date: 2026-05-22 03:21:56.297619
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "02eee99fe6ae"
down_revision: str | Sequence[str] | None = "80b390245151"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("confluence_base_url", sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "confluence_base_url")
    # ### end Alembic commands ###
