"""Add conversation_data to threads

Revision ID: 0fc71b7d1092
Revises: e1287c77977a
Create Date: 2026-06-03 15:52:10.522065
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0fc71b7d1092"
down_revision: str | Sequence[str] | None = "e1287c77977a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("threads", sa.Column("conversation_data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "conversation_data")
    # ### end Alembic commands ###
