"""Add TestAccountCredential model

Revision ID: 100481f3bba1
Revises: 66ce77ac9470
Create Date: 2026-06-25 21:26:37.539955
"""

from collections.abc import Sequence

import sqlalchemy as sa

import ai_qa.db.types
from alembic import op

revision: str = "100481f3bba1"
down_revision: str | Sequence[str] | None = "66ce77ac9470"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_account_credentials",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("environment", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column(
            "username", ai_qa.db.types.UserSecretEncryptedString(length=1024), nullable=False
        ),
        sa.Column(
            "password", ai_qa.db.types.UserSecretEncryptedString(length=1024), nullable=False
        ),
        sa.Column(
            "totp_secret", ai_qa.db.types.UserSecretEncryptedString(length=1024), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_test_account_credentials_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_account_credentials")),
        sa.UniqueConstraint(
            "project_id", "environment", "role", name="uq_test_account_credentials_project_env_role"
        ),
    )
    op.create_index(
        "ix_test_account_credentials_project",
        "test_account_credentials",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_account_credentials_project_id"),
        "test_account_credentials",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_test_account_credentials_project_id"), table_name="test_account_credentials"
    )
    op.drop_index("ix_test_account_credentials_project", table_name="test_account_credentials")
    op.drop_table("test_account_credentials")
    # ### end Alembic commands ###
