"""add ancestor_source_ids to artifacts

Revision ID: 2c89cf36f942
Revises: 100481f3bba1
Create Date: 2026-06-26 10:01:17.797017
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2c89cf36f942"
down_revision: str | Sequence[str] | None = "100481f3bba1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artifacts", sa.Column("ancestor_source_ids", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artifacts", "ancestor_source_ids")
    # ### end Alembic commands ###
