"""Add provider to DiscoveredModelSnapshot

Revision ID: 4b6275b93c8a
Revises: a6e9fdf81829
Create Date: 2026-07-01 20:21:41.362036
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4b6275b93c8a"
down_revision: str | Sequence[str] | None = "a6e9fdf81829"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("discovered_models", sa.Column("provider", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("discovered_models", "provider")
    # ### end Alembic commands ###
