"""Move conversation data to messages

Revision ID: 60eb63abe6a6
Revises: b7d2f1a9c4e5
Create Date: 2026-06-08 14:12:24.566111
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "60eb63abe6a6"
down_revision: str | Sequence[str] | None = "b7d2f1a9c4e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("sender", sa.String(length=50), nullable=False))
    op.add_column("messages", sa.Column("agent_name", sa.String(length=50), nullable=True))
    op.add_column("messages", sa.Column("message_type", sa.String(length=50), nullable=False))
    op.add_column("messages", sa.Column("message_metadata", sa.JSON(), nullable=True))
    op.drop_column("messages", "role")
    op.drop_constraint(op.f("uq_projects_name"), "projects", type_="unique")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=True)
    op.add_column("threads", sa.Column("current_agent", sa.String(length=50), nullable=False))
    op.drop_column("threads", "conversation_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "threads",
        sa.Column(
            "conversation_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("threads", "current_agent")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_unique_constraint(
        op.f("uq_projects_name"), "projects", ["name"], postgresql_nulls_not_distinct=False
    )
    op.add_column(
        "messages", sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=False)
    )
    op.drop_column("messages", "message_metadata")
    op.drop_column("messages", "message_type")
    op.drop_column("messages", "agent_name")
    op.drop_column("messages", "sender")
    # ### end Alembic commands ###
