"""drop users.password_hash

Revision ID: 66ce77ac9470
Revises: 91db599bf684
Create Date: 2026-06-25 20:11:31.988147
"""

from collections.abc import Sequence

revision: str = "66ce77ac9470"
down_revision: str | Sequence[str] | None = "91db599bf684"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
