"""cascade_all_relations

Revision ID: 6b50f6ce4d9e
Revises: c1f242933147
Create Date: 2026-06-04 16:39:18.898729
"""

from collections.abc import Sequence

from alembic import op

revision: str = "6b50f6ce4d9e"
down_revision: str | Sequence[str] | None = "c1f242933147"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_artifact_versions_created_by_user_id_users"),
        "artifact_versions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_artifact_versions_created_by_user_id_users"),
        "artifact_versions",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_artifacts_pipeline_run_id_pipeline_runs"), "artifacts", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_artifacts_pipeline_run_id_pipeline_runs"),
        "artifacts",
        "pipeline_runs",
        ["pipeline_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_audit_events_project_id_projects"), "audit_events", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_audit_events_user_id_users"), "audit_events", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_audit_events_pipeline_run_id_pipeline_runs"), "audit_events", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_audit_events_project_id_projects"),
        "audit_events",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_audit_events_pipeline_run_id_pipeline_runs"),
        "audit_events",
        "pipeline_runs",
        ["pipeline_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_audit_events_user_id_users"),
        "audit_events",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_pipeline_runs_started_by_user_id_users"), "pipeline_runs", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_pipeline_runs_project_id_projects"), "pipeline_runs", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_pipeline_runs_started_by_user_id_users"),
        "pipeline_runs",
        "users",
        ["started_by_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_pipeline_runs_project_id_projects"),
        "pipeline_runs",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("fk_projects_created_by_user_id_users"), "projects", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_projects_created_by_user_id_users"),
        "projects",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_projects_created_by_user_id_users"), "projects", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_projects_created_by_user_id_users"),
        "projects",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("fk_pipeline_runs_project_id_projects"), "pipeline_runs", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_pipeline_runs_started_by_user_id_users"), "pipeline_runs", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_pipeline_runs_project_id_projects"),
        "pipeline_runs",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_pipeline_runs_started_by_user_id_users"),
        "pipeline_runs",
        "users",
        ["started_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(op.f("fk_audit_events_user_id_users"), "audit_events", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_audit_events_pipeline_run_id_pipeline_runs"), "audit_events", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_audit_events_project_id_projects"), "audit_events", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_audit_events_pipeline_run_id_pipeline_runs"),
        "audit_events",
        "pipeline_runs",
        ["pipeline_run_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_audit_events_user_id_users"),
        "audit_events",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_audit_events_project_id_projects"),
        "audit_events",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("fk_artifacts_pipeline_run_id_pipeline_runs"), "artifacts", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_artifacts_pipeline_run_id_pipeline_runs"),
        "artifacts",
        "pipeline_runs",
        ["pipeline_run_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("fk_artifact_versions_created_by_user_id_users"),
        "artifact_versions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_artifact_versions_created_by_user_id_users"),
        "artifact_versions",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
