"""Add workspace storage migration

Revision ID: 80b390245151
Revises: 20260504_1201
Create Date: 2026-05-21 21:01:46.300680
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "80b390245151"
down_revision: str | Sequence[str] | None = "20260504_1201"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("current_step", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "projects",
        sa.Column("status", sa.String(length=50), server_default="'start'", nullable=False),
    )
    op.add_column(
        "projects",
        sa.Column(
            "conversation_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "ai_provider_config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "ai_agents_config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(
        op.f("uq_users_email"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("users", "ai_agents_config")
    op.drop_column("users", "ai_provider_config")
    op.drop_column("users", "settings")
    op.drop_column("projects", "conversation_data")
    op.drop_column("projects", "status")
    op.drop_column("projects", "current_step")
    # ### end Alembic commands ###
