"""merge_thread_agent_configs_and_clean_up

Revision ID: 8f604df875ba
Revises: ec093208caf6
Create Date: 2026-06-05 13:23:34.643667
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "8f604df875ba"
down_revision: str | Sequence[str] | None = "ec093208caf6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_thread_agent_configs_thread_id"), table_name="thread_agent_configs")
    op.drop_table("thread_agent_configs")
    op.add_column("threads", sa.Column("agent_configs", sa.JSON(), nullable=True))

    # Ensure pipeline_runs is dropped, regardless of previous migration failures
    try:
        # SQLite compatible
        op.execute("DROP TABLE IF EXISTS pipeline_runs")
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "agent_configs")
    op.create_table(
        "thread_agent_configs",
        sa.Column("thread_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("agent_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("model_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
            name=op.f("fk_thread_agent_configs_thread_id_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thread_agent_configs")),
        sa.UniqueConstraint(
            "thread_id",
            "agent_name",
            name=op.f("uq_thread_agent"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_thread_agent_configs_thread_id"),
        "thread_agent_configs",
        ["thread_id"],
        unique=False,
    )
    # ### end Alembic commands ###
