"""make testaccountcredential user scoped

Revision ID: a6e9fdf81829
Revises: 972663fc8da1
Create Date: 2026-06-27 01:16:48.137826
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a6e9fdf81829"
down_revision: str | Sequence[str] | None = "972663fc8da1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Preserve in-use credentials instead of wiping them: add user_id nullable, backfill
    # the owner from the project's creator, then enforce NOT NULL. Only rows that genuinely
    # cannot be mapped to a user (project has no creator) are dropped. (The original
    # auto-generated upgrade did `DELETE FROM test_account_credentials`, which destroyed all
    # in-use rows on every apply/re-apply — that data loss is what this avoids.)
    op.add_column("test_account_credentials", sa.Column("user_id", sa.UUID(), nullable=True))
    op.execute(
        """
        UPDATE test_account_credentials AS c
        SET user_id = p.created_by_user_id
        FROM projects AS p
        WHERE c.project_id = p.id
          AND c.user_id IS NULL
          AND p.created_by_user_id IS NOT NULL
        """
    )
    op.execute("DELETE FROM test_account_credentials WHERE user_id IS NULL")
    op.alter_column("test_account_credentials", "user_id", nullable=False)
    op.drop_index(
        op.f("ix_test_account_credentials_project"), table_name="test_account_credentials"
    )
    op.drop_constraint(
        op.f("uq_test_account_credentials_project_env_role"),
        "test_account_credentials",
        type_="unique",
    )
    op.create_index(
        op.f("ix_test_account_credentials_user_id"),
        "test_account_credentials",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_test_account_credentials_user_project",
        "test_account_credentials",
        ["user_id", "project_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_test_account_credentials_user_project_env_role",
        "test_account_credentials",
        ["user_id", "project_id", "environment", "role"],
    )
    op.create_foreign_key(
        op.f("fk_test_account_credentials_user_id_users"),
        "test_account_credentials",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_test_account_credentials_user_id_users"),
        "test_account_credentials",
        type_="foreignkey",
    )
    op.drop_constraint(
        "uq_test_account_credentials_user_project_env_role",
        "test_account_credentials",
        type_="unique",
    )
    op.drop_index("ix_test_account_credentials_user_project", table_name="test_account_credentials")
    op.drop_index(
        op.f("ix_test_account_credentials_user_id"), table_name="test_account_credentials"
    )
    op.create_unique_constraint(
        op.f("uq_test_account_credentials_project_env_role"),
        "test_account_credentials",
        ["project_id", "environment", "role"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_test_account_credentials_project"),
        "test_account_credentials",
        ["project_id"],
        unique=False,
    )
    op.drop_column("test_account_credentials", "user_id")
    # ### end Alembic commands ###
