"""add chrome_path to user

Revision ID: ac0c253d7bc4
Revises: 0fc71b7d1092
Create Date: 2026-06-04 09:34:14.735406
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ac0c253d7bc4"
down_revision: str | Sequence[str] | None = "0fc71b7d1092"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("chrome_path", sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "chrome_path")
    # ### end Alembic commands ###
