"""Move conversation state to Thread and add Message model

Revision ID: bea4e09bf61a
Revises: 96422e797dd0
Create Date: 2026-06-01 16:54:54.039720
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "bea4e09bf61a"
down_revision: str | Sequence[str] | None = "96422e797dd0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
            name=op.f("fk_messages_thread_id_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(op.f("ix_messages_thread_id"), "messages", ["thread_id"], unique=False)
    op.drop_column("projects", "conversation_data")
    op.drop_column("projects", "status")
    op.drop_column("projects", "current_step")
    op.add_column("threads", sa.Column("current_step", sa.Integer(), nullable=False))
    op.add_column("threads", sa.Column("status", sa.String(length=50), nullable=False))
    op.drop_column("threads", "conversation_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "threads",
        sa.Column(
            "conversation_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("threads", "status")
    op.drop_column("threads", "current_step")
    op.add_column(
        "projects",
        sa.Column(
            "current_step",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "status",
            sa.VARCHAR(length=50),
            server_default=sa.text("'''start'''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "conversation_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_messages_thread_id"), table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
