"""cascade_delete_threads_project

Revision ID: c1f242933147
Revises: ac0c253d7bc4
Create Date: 2026-06-04 15:55:16.028091
"""

from collections.abc import Sequence

from alembic import op

revision: str = "c1f242933147"
down_revision: str | Sequence[str] | None = "ac0c253d7bc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_threads_project_id_projects"), "threads", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_threads_project_id_projects"),
        "threads",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_threads_project_id_projects"), "threads", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_threads_project_id_projects"),
        "threads",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
