"""Move agent config to thread

Revision ID: e1287c77977a
Revises: bea4e09bf61a
Create Date: 2026-06-02 14:10:35.999981
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import ai_qa.db.types
from alembic import op

revision: str = "e1287c77977a"
down_revision: str | Sequence[str] | None = "bea4e09bf61a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread_agent_configs",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=50), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
            name=op.f("fk_thread_agent_configs_thread_id_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thread_agent_configs")),
        sa.UniqueConstraint("thread_id", "agent_name", name="uq_thread_agent"),
    )
    op.create_index(
        op.f("ix_thread_agent_configs_thread_id"),
        "thread_agent_configs",
        ["thread_id"],
        unique=False,
    )
    op.add_column("threads", sa.Column("provider_name", sa.String(length=50), nullable=True))
    op.add_column("threads", sa.Column("provider_base_url", sa.String(length=512), nullable=True))
    op.add_column(
        "users",
        sa.Column("browser_use_key", ai_qa.db.types.EncryptedString(length=512), nullable=True),
    )
    op.add_column(
        "users", sa.Column("claude_key", ai_qa.db.types.EncryptedString(length=512), nullable=True)
    )
    op.add_column(
        "users", sa.Column("gemini_key", ai_qa.db.types.EncryptedString(length=512), nullable=True)
    )
    op.add_column(
        "users", sa.Column("openai_key", ai_qa.db.types.EncryptedString(length=512), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("on_premises_key", ai_qa.db.types.EncryptedString(length=512), nullable=True),
    )
    op.add_column(
        "users", sa.Column("mcp_key", ai_qa.db.types.EncryptedString(length=512), nullable=True)
    )
    op.drop_column("users", "ai_provider_config")
    op.drop_column("users", "ai_agents_config")
    op.drop_column("users", "settings")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "ai_agents_config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "ai_provider_config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "mcp_key")
    op.drop_column("users", "on_premises_key")
    op.drop_column("users", "openai_key")
    op.drop_column("users", "gemini_key")
    op.drop_column("users", "claude_key")
    op.drop_column("users", "browser_use_key")
    op.drop_column("threads", "provider_base_url")
    op.drop_column("threads", "provider_name")
    op.drop_index(op.f("ix_thread_agent_configs_thread_id"), table_name="thread_agent_configs")
    op.drop_table("thread_agent_configs")
    # ### end Alembic commands ###
