"""drop pipeline_runs

Revision ID: ec093208caf6
Revises: 0d5fd025248e
Create Date: 2026-06-05 10:13:58.650994
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ec093208caf6"
down_revision: str | Sequence[str] | None = "0d5fd025248e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_agent_runs_thread_status", "agent_runs", ["thread_id", "status"], unique=False
    )
    op.create_index("ix_threads_project_user", "threads", ["project_id", "user_id"], unique=False)
    # ### end Alembic commands ###

    # Drop legacy columns and table if they exist
    op.execute("ALTER TABLE artifacts DROP COLUMN IF EXISTS legacy_pipeline_run_id CASCADE")
    op.execute("ALTER TABLE audit_events DROP COLUMN IF EXISTS legacy_pipeline_run_id CASCADE")
    op.execute("DROP TABLE IF EXISTS pipeline_runs CASCADE")


def downgrade() -> None:
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("trigger_source", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legacy_retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legacy_retirement_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_pipeline_runs_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_pipeline_runs"),
    )
    op.create_index("ix_pipeline_runs_project_id", "pipeline_runs", ["project_id"], unique=False)

    op.add_column("audit_events", sa.Column("legacy_pipeline_run_id", sa.UUID(), nullable=True))
    op.create_index(
        "ix_audit_events_legacy_pipeline_run_id",
        "audit_events",
        ["legacy_pipeline_run_id"],
        unique=False,
    )

    op.add_column("artifacts", sa.Column("legacy_pipeline_run_id", sa.UUID(), nullable=True))
    op.create_index(
        "ix_artifacts_legacy_pipeline_run_id", "artifacts", ["legacy_pipeline_run_id"], unique=False
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_threads_project_user", table_name="threads")
    op.drop_index("ix_agent_runs_thread_status", table_name="agent_runs")
    # ### end Alembic commands ###
