import { useEffect, useId, useRef, useState } from "react";
import mermaid from "mermaid";

interface MermaidDiagramProps {
  chart: string;
}

let mermaidInitialized = false;

function ensureMermaidInitialized() {
  if (!mermaidInitialized) {
    mermaid.initialize({
      startOnLoad: false,
      theme: "default",
      securityLevel: "strict",
    });
    mermaidInitialized = true;
  }
}

/**
 * Renders a Mermaid diagram from a chart string.
 *
 * - Calls mermaid.render() imperatively (not startOnLoad).
 * - Uses useId() for a deterministic, unique render ID per component instance.
 * - Guards against React StrictMode double-invoke with a `cancelled` ref.
 * - Falls back to a <pre> block with an error note if the chart fails to parse.
 *
 * D1 (Story 10-3): standalone kind="mermaid" in ArtifactPreview, plus additive
 * language="mermaid" branch in ReviewContent for ```mermaid blocks.
 */
export function MermaidDiagram({ chart }: MermaidDiagramProps) {
  const reactId = useId();
  // mermaid render IDs must start with a letter and be alphanumeric-safe.
  const renderId = `mermaid-${reactId.replace(/[^a-zA-Z0-9]/g, "")}`;

  const [svg, setSvg] = useState<string | null>(null);
  const [renderError, setRenderError] = useState<string | null>(null);
  const cancelledRef = useRef(false);

  useEffect(() => {
    cancelledRef.current = false;

    let active = true;
    const cancelled = () => cancelledRef.current || !active;

    async function render() {
      try {
        ensureMermaidInitialized();
        const result = await mermaid.render(renderId, chart);
        if (!cancelled()) {
          setSvg(result.svg);
          setRenderError(null);
        }
      } catch (err) {
        if (!cancelled()) {
          setSvg(null);
          setRenderError(
            err instanceof Error ? err.message : "Diagram could not be rendered",
          );
        }
      }
    }

    render();

    return () => {
      active = false;
      cancelledRef.current = true;
    };
  }, [chart, renderId]);

  if (renderError !== null) {
    return (
      <div className="my-4">
        <p className="text-xs text-amber-600 mb-1">⚠ Diagram could not be rendered</p>
        <pre className="bg-slate-100 text-slate-700 p-3 rounded text-xs overflow-x-auto whitespace-pre-wrap break-words">
          {chart}
        </pre>
      </div>
    );
  }

  if (svg === null) {
    return (
      <div className="my-4 text-xs text-slate-400 italic">Rendering diagram…</div>
    );
  }

  return (
    <div
      className="my-4 max-w-full overflow-x-auto"
      // svg is generated by the mermaid library (trusted, sanitized output)
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
